

CREATE TABLE albums(
    album_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    album_name TEXT NOT NULL); 
CREATE TABLE photos(
    photo_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    album_id INTEGER NOT NULL,
    photo_name TEXT NOT NULL,
    fullsize BLOB NOT NULL,
    thumbnail BLOB NOT NULL,
    FOREIGN KEY(album_id) REFERENCES albums(album_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB; CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username TEXT NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL UNIQUE
);